# Codecov configuration for space_packet_parser
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  status:
    project:
      default:
        target: 85% # Target coverage percentage
        threshold: 5% # Allow 5% drop without failing
        if_no_uploads: error # Fail if no coverage data
        only_pulls: false # Check coverage on all commits

      # Custom group for tests module with higher threshold
      tests:
        target: 95% # Very high threshold for test files
        threshold: 1% # Allow only 1% drop
        paths:
          - "tests/**" # Adjust this path to match your test directory
        if_no_uploads: error
        only_pulls: false

    patch:
      default:
        target: 85% # Lower threshold for new code
        threshold: 5%
        only_pulls: true # Only check patch coverage on PRs

  ignore:
    - "bin/**/*" # Don't include utility scripts
    - "docs/**/*" # Don't include documentation
